version: "2"
services:
  nodejs:
    image: felipearaujo/nps-nlw:latest
    build: .
    ports:
      - 4000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432
