version: "3"
services:
  postgres:
    container_name: "db"
    image: "postgres:11.2"
    environment:
      POSTGRES_USER: nlw
      POSTGRES_PASSWORD: nlw
      POSTGRES_DB: "nlw-nps"
    ports:
      - "5432:5432"

  postgres_data:
    image: felipearaujo/nps-nlw:latest
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "4000:4000"
